name: Spell Check

on:
  push:
    paths:
      - '**.md'

jobs:
  check-spelling:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install codespell
        run: pip install codespell

      - name: Run codespell
        run: codespell .
