name: Spell Check

on:
  push:
    paths:
      - '**.md'

jobs:
  check-spelling:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install codespell
        run: pip install codespell

      - name: Run codespell
        run: |
          codespell . > result.txt || true
          cat result.txt
          if [ ! -s result.txt ]; then
            echo "✅ No spelling errors found."
          else
            echo "⚠️ Spelling errors detected."
          fi
