name: Auto Fix Spelling and Create PR

on:
  push:
    paths:
      - '**.md'

jobs:
  auto-fix-spelling:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install codespell
        run: pip install codespell

      - name: Fix spelling mistakes
        run: codespell -w .

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Create or switch to spelling-fixes branch
        run: |
          git fetch origin
          git checkout -B spelling-fixes

      - name: Commit and push changes
        env:
          TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        run: |
          git add .
          git commit -m "Fix spelling mistakes by codespell" || echo "Nothing to commit"
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}
          git push origin spelling-fixes --force

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          commit-message: Fix spelling mistakes by codespell
          branch: spelling-fixes
          title: Fix spelling mistakes by codespell
          body: This PR fixes spelling mistakes detected by codespell.
          draft: false
