name: Spell Check with PR Comment

on:
  push:
    paths:
      - '**.md'
  pull_request:
    paths:
      - '**.md'

jobs:
  check-spelling:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install codespell
        run: pip install codespell

      - name: Run codespell and save output
        id: spellcheck
        run: |
          codespell . > result.txt || true
          cat result.txt
        continue-on-error: true

      - name: Comment spellcheck results on PR
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const result = fs.readFileSync('result.txt', 'utf8').trim();

            if (!result) {
              // ไม่มีคำผิด
              return github.rest.issues.createComment({
                issue_number: context.payload.pull_request.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: '✅ ไม่มีคำสะกดผิดใน Markdown files ครับ!'
              });
            } else {
              // มีคำผิด แจ้งรายละเอียด
              const commentBody = `⚠️ พบคำสะกดผิดใน Markdown files:\n\n` + 
                '```\n' + result + '\n```';
              return github.rest.issues.createComment({
                issue_number: context.payload.pull_request.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: commentBody
              });
            }
