name: Auto Fix Spelling and Create PR

on:
  push:
    paths:
      - '**.md'

jobs:
  auto-fix-spelling:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install codespell
        run: pip install codespell

      - name: Fix spelling mistakes
        run: codespell -w .

      - name: Setup spelling-fixes branch
        run: |
          git fetch origin
          git checkout -b spelling-fixes || git checkout spelling-fixes

      - name: Commit fixed files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Fix spelling mistakes by codespell
          branch: spelling-fixes
          push_options: '--force'

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Fix spelling mistakes by codespell
          branch: spelling-fixes
          title: Fix spelling mistakes by codespell
          body: This PR fixes spelling mistakes detected by codespell.
          draft: false
